import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { getSession } from '@/lib/auth';
import NavigationHeader from '@/components/NavigationHeader';
import { Analytics } from '@vercel/analytics/react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dfence Prep - AI Powered Exam Preparation',
  description: 'Daily news, quizzes, and MCQ generated by AI for Defence exams.',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getSession();

  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className={`${inter.className} bg-slate-50 text-slate-900 min-h-screen flex flex-col overflow-x-hidden`}>
        <NavigationHeader session={session} />
        <main className="flex-1 container mx-auto px-4 py-8">
          {children}
        </main>
        <footer className="border-t py-6 bg-white mt-auto">
          <div className="container mx-auto px-4 flex flex-col md:flex-row items-center justify-between text-sm text-slate-500">
            <p>© {new Date().getFullYear()} DfencePrep. All rights reserved.</p>
            <div className="flex space-x-4 mt-4 md:mt-0">
              <Link href="/admin" className="hover:text-slate-900">Admin</Link>
            </div>
          </div>
        </footer>
        <Analytics />
      </body>
    </html>
  )
}
